/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iterface.algorithm;

import algorithm.MyAlgorithm4;
import common.SensorUtility;
import static common.SensorUtility.mListSensorNodes;
import javax.swing.JOptionPane;

/**
 *
 * @author dauto98
 */
public class frameMyAlgorithm4 extends javax.swing.JFrame {

    /**
     * Creates new form frameMyAlgorithm4
     */
    public frameMyAlgorithm4() {
        initComponents();
        NumberOfSensorLabel.setText("Number of Sensor : "+mListSensorNodes.size());
    }
    
    void clearData(){
//        TimeRunningLabel.setText("TimeRunning : 0 ");
//        dataSensorModel.clear();
//        dataListXModel.clear();
//        ListSensor.clear();
//        totalTimeOnLabel.setText("Total Time ON : 0");
//        listXLabel.setText("ListX(time) : 0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumberOfSensorLabel = new javax.swing.JLabel();
        LValueText = new javax.swing.JLabel();
        LifeTimeSensorText = new javax.swing.JLabel();
        LValueTextField = new javax.swing.JTextField();
        LifeTimeOfSensorTextField = new javax.swing.JTextField();
        runButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumberOfSensorLabel.setText("Number of sensors: ");

        LValueText.setText("L value");

        LifeTimeSensorText.setText("Life time of the sensor(s)");

        LValueTextField.setText("2");
        LValueTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LValueTextFieldKeyReleased(evt);
            }
        });

        LifeTimeOfSensorTextField.setText("3000");
        LifeTimeOfSensorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LifeTimeOfSensorTextFieldKeyReleased(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Result");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 401, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberOfSensorLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LifeTimeSensorText)
                                    .addComponent(LValueText))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(runButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LifeTimeOfSensorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(LValueTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NumberOfSensorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LValueText)
                    .addComponent(LValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LifeTimeSensorText)
                    .addComponent(LifeTimeOfSensorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(runButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        if (mListSensorNodes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insert sensorr nodes");
        } else {
            clearData();
            MyAlgorithm4 myAlgorithm = new MyAlgorithm4();
            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    long begin = System.currentTimeMillis();
                    myAlgorithm.run();
                    long end = System.currentTimeMillis();
                    long timeRun = end-begin;
//                    updateListX();
//                    displayResult();
                }
            });
            thread.start();
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void LValueTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LValueTextFieldKeyReleased
        try {
            SensorUtility.Lvalue = Integer.parseInt(LValueTextField.getText());
        } catch (NumberFormatException nfe) {
            LValueTextField.setText("");
        }
    }//GEN-LAST:event_LValueTextFieldKeyReleased

    private void LifeTimeOfSensorTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LifeTimeOfSensorTextFieldKeyReleased
        try {
            SensorUtility.LifeTimeOfSensor = Integer.parseInt(LifeTimeOfSensorTextField.getText());
        } catch (NumberFormatException nfe) {
            LifeTimeOfSensorTextField.setText("");
        }
    }//GEN-LAST:event_LifeTimeOfSensorTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMyAlgorithm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMyAlgorithm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMyAlgorithm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMyAlgorithm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMyAlgorithm4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LValueText;
    private javax.swing.JTextField LValueTextField;
    private javax.swing.JTextField LifeTimeOfSensorTextField;
    private javax.swing.JLabel LifeTimeSensorText;
    private javax.swing.JLabel NumberOfSensorLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
